version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: ./django-site/Dockerfile.front
    ports:
      - "8001:8001"
    depends_on:
      - db
      - api

  api:
    build:
      context: .
      dockerfile: ./django-site/Dockerfile.api
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: bookdb
      POSTGRES_USER: yosser
      POSTGRES_PASSWORD: 2021
    ports:
      - "5432:5432"

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - api
